### ISSUE TITLE
How to push to the pull request?

### ISSUE THREAD

**Issue by NatoBoram** [qoomon/actions--create-commit#3]
If I copy the [example](https://github.com/coderabbitai/coderabbit-docs/actions/runs/11632860773/job/32396834289) in `README.md`, I get this:

```log
Run git push
  git push
  shell: /usr/bin/bash -e {0}
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Error: Process completed with exit code 128.
```

If I do `git push origin '${{ github.head_ref }}'` [instead](https://github.com/coderabbitai/coderabbit-docs/actions/runs/11633129341/job/32397642603), I get 

```log
Run git push origin 'bugfix/pnpm-lint-fix'
  git push origin 'bugfix/pnpm-lint-fix'
  shell: /usr/bin/bash -e {0}
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
error: src refspec bugfix/pnpm-lint-fix does not match any
error: failed to push some refs to 'https://github.com/coderabbitai/coderabbit-docs'
Error: Process completed with exit code 1.
```

**Comment by qoomon** [comment]
My bad. You need to pass the branch as an input parameter of the checkout action to checkout a branch instead of a commit in detached HEAD mode.

```yaml
- uses: actions/checkout@master
  with:
    ref: ${{ github.ref }}
```

**Comment by NatoBoram** [comment]
GitHub changed how `github.ref` works. In pull requests, it becomes `refs/pull/131/merge`.

Here's another way to make it work in pull requests:

```yaml
steps:
  - uses: actions/checkout@v4
    with:
      ref: ${{ github.head_ref || github.ref }}
```
