### ISSUE TITLE
Create an annotated tag

### ISSUE THREAD

**Issue by NatoBoram** [qoomon/actions--create-commit#4]
When releasing new versions, we have to bump the version number in the project, create a git commit then create a git tag.

I'd like to be able to use this action in that context.

This could be done with something like that:

```yaml
- uses: qoomon/actions--create-commit@v1
  id: commit
  with:
    message: work work
    skip-empty: true
    tag: true
    tag-message: work work?

- if: ${{ steps.commit.outputs.commit }}
  run: git push
```
